CREATE USER gpadmin_gr WITH ENCRYPTED PASSWORD 'gpadmin_S112754AA';
ALTER ROLE gpadmin_gr WITH VALID UNTIL 'infinity';
GRANT CONNECT ON DATABASE postgres TO gpadmin_gr;
GRANT USAGE ON SCHEMA public TO gpadmin_gr;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gpadmin_gr;